{
 "title": "test fr-bck",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "frontend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "frequenza" }
   ],
   "targets": [
    {
     "expr": "rate( frt_consumer_valide_totali[1m] )",
     "legendFormat": "valide {{method}}"
    },
    {
     "expr": "rate( frt_consumer_errori_totali[1m] )",
     "legendFormat": "errori {{method}}"
    }
   ]
  },
  {
   "title": "jetty response code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "pps", "label": "frequenza" }
   ],
   "targets": [
    {
     "expr": " rate(jetty_responses_total[1m])",
     "legendFormat": "response {{job}}{{code}}"
    }
   ]
  },
  {
   "title": "backend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "frequenza" }
   ],
   "targets": [
    { "expr": " rate(bck_api_total[1m])" }
   ]
  },
  {
   "title": "jetty dispatched",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "frequenza" }
   ],
   "targets": [
    {
     "expr": " rate(jetty_requests_total[1m])",
     "legendFormat": "request {{job}}"
    }
   ]
  }
 ]
}